# Generated by Django 4.1.7 on 2023-03-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(max_length=2000),
        ),
    ]
