# Generated by Django 4.1.7 on 2023-03-21 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='autores/%d-%b')),
                ('biografia', models.TextField(max_length=1000)),
                ('nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('morte', models.DateField(blank=True, help_text='Caso ainda vivo, deixar em branco', null=True, verbose_name='Data de morte')),
                ('frase_destaque', models.TextField(blank=True, max_length=200, null=True, verbose_name='Frase exibida no perfil')),
            ],
        ),
        migrations.CreateModel(
            name='GeneroLiterario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sinopse', models.TextField(max_length=1000)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livraria.autor')),
                ('genero_literario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livraria.generoliterario')),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='genero_literario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livraria.generoliterario'),
        ),
    ]
